name: update123456

on:
  schedule:
    - cron: '*/10 * * * *'  # 每 10 分钟运行一次
  workflow_dispatch:  # 手动触发

jobs:
  run_scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8  # 使用 Python 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium requests pandas webdriver-manager tabulate

    # 确保 TXT 文件同步到运行环境
    - name: Ensure TXT files exist
      run: |
        touch earthquake_data.txt
        touch latest_earthquake_data.txt

    # 运行地震情报脚本
    - name: Run earthquake scraper
      run: |
        python 123456.py
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

    # 将更新后的 TXT 文件推送回仓库
    - name: Commit and push updated TXT files
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add earthquake_data.txt latest_earthquake_data.txt
        git commit -m "Update earthquake data files"
        git push
      continue-on-error: true
