name: update123456

on:
  workflow_dispatch:  # 手动触发

jobs:
  run_scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # 拉取完整历史，确保能够访问所有的文件和分支

    - name: Ensure TXT files are up-to-date
      run: |
        # 拉取最新的仓库内容
        git fetch --all
        git reset --hard origin/${{ github.ref_name }}

    - name: Debug TXT files
      run: |
        echo "earthquake_data.txt 内容："
        cat earthquake_data.txt || echo "文件不存在或为空"
        echo "latest_earthquake_data.txt 内容："
        cat latest_earthquake_data.txt || echo "文件不存在或为空"

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium requests pandas webdriver-manager tabulate

    - name: Run earthquake scraper
      run: |
        python 123456.py
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

    - name: Commit and push updated TXT files
      run: |
        # 配置 Git 用户信息
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
        # 添加更新后的文件并提交
        git add earthquake_data.txt latest_earthquake_data.txt
        git commit -m "Update earthquake data files"
        
        # 推送更新回 GitHub 仓库
        git push "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:${{ github.ref_name }}
