name: update123456

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: "*/5 * * * *"  # 每5分钟执行一次

jobs:
  run_scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # 拉取完整历史

    - name: Ensure TXT files are up-to-date
      run: |
        git fetch --all
        git reset --hard origin/${{ github.ref_name }}

    - name: Debug TXT files
      run: |
        echo "earthquake_data.txt 内容："
        cat earthquake_data.txt || echo "文件不存在或为空"
        echo "latest_earthquake_data.txt 内容："
        cat latest_earthquake_data.txt || echo "文件不存在或为空"

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium requests pandas webdriver-manager tabulate

    - name: Run earthquake scraper
      run: |
        python 123456.py
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

    - name: Commit and push updated TXT files
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
        # 检查是否有更改
        git diff --exit-code || (git add earthquake_data.txt latest_earthquake_data.txt && git commit -m "Update earthquake data files")

        # 推送更改
        git push "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:${{ github.ref_name }}
